# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
# This committed copy is a template until the first release fills in real checksums.
cask "csx" do
  version "0.0.0"

  on_macos do
    on_arm do
      sha256 :no_check
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 :no_check
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-x86_64-apple-darwin.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 :no_check
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
    end
    on_intel do
      sha256 :no_check
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  name "csx"
  desc "Local full-text + hybrid search across AI-coding sessions"
  homepage "https://github.com/mysqto/csx"

  binary "csx"
end
