# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
cask "csx" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "46eca795b0a3df41a1fece2b01c3e871eddf3a51ec808bfef8b367efd42cce89"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "16c2fd91385105d0dcad14d0dd10fc8031b058cfb2af428f6833c4aca1ef1533"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-x86_64-apple-darwin.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fa17c2bd0c437d52b65bef297fa44578473676d84f222ab4dbe121ed9c9732d1"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
    end
    on_intel do
      sha256 "2217578674ae7d949081013c2c002677d8e721dd4168a7309f9e8c5e419d6392"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  name "csx"
  desc "Local full-text + hybrid search across AI-coding sessions"
  homepage "https://github.com/mysqto/csx"

  binary "csx"
end
