# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
cask "csx" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "261d71863545bba7ccc38d7a7504bb3b03a8abbfd558a0c19245eb3ad92a3650"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "7b3bb561735bcf84147f196760b3af6b30c1dbee74ea63f06166b09cbcf4c565"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-x86_64-apple-darwin.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b29d767845724622533df68f9810a2ab8de359d142e1c1fbe807c1a2a59bb38"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
    end
    on_intel do
      sha256 "112a6689acb85fc3c6c4be502f4b030b2762fd7ff02d3d4a37dd0e6da2e3765f"
      url "https://github.com/mysqto/csx/releases/download/v#{version}/csx-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  name "csx"
  desc "Local full-text + hybrid search across AI-coding sessions"
  homepage "https://github.com/mysqto/csx"

  binary "csx"
end
